### ISSUE TITLE
Staff & Vols list / management improvements

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#1]
**Module**
Staff & Vols

**Detailed Description**

1. Admin users should be able to see users from all states available to them.
2. There should be filters for state, campaign, and role above the list.
3. By default, the user list will be filtered by the admin user's selected state.

**Urgency**
2

**Comment by rbrtmnz** [comment]
I can see that point number 2 exists but without the ability to create additional roles in staging I cannot test points 1 or 3.

**Comment by codygordon** [comment]
I restored the roles from prod (and you should also be able to create new ones).

**Comment by codygordon** [comment]
@rbrtmnz – this is deployed to prod. 

Also note something useful: if you select `all` for the **state**, **campaign**, and **status** filters you can select `Legacy User` in **role** and add campaigns or admin role to those users.
