### ISSUE TITLE
Allow canvass results to be uploaded for all campaigns

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#10]
**Module**
Bulk Upload

**Detailed Description**
Allow canvass results IDs to be uploaded to "All Campaigns". Will only be able to show statewide canvass questions as upload options.

**Urgency**
1

**Comment by rbrtmnz** [comment]
This functionality does not appear to exist.

**Comment by rbrtmnz** [comment]
The functionality exists but the "Start Upload" button is grayed out. I tried a few times and no matter what I did it never became clickable.

**Comment by codygordon** [comment]
Doh – this is fixed.

**Comment by rbrtmnz** [comment]
Looks good!
