### ISSUE TITLE
Send contacts to Spoke from targeting universe

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#17]
**Module**
Targeting

**Detailed Description**
- To get this done ASAP I'm just connecting directly to the Spoke Postgres database in lieu of a Spoke API we can interact with, which would take significant effort to implement (but would be nice to do down the line if I ever have time to actually contribute to Spoke dev....). The risk here is if the db URI changes in Spoke it also needs to be changed in the Votivate settings, so I need to be alerted when you plan to scale up / down the db.

- On the targeting panel there will be a button for specific users called "Send to Spoke".

- When the button is pressed a modal appears that allows you to search for a spoke campaign. The search only pulls campaigns that have not been started, which simplifies things. I just figure this will be a good safeguard against accidentally replacing a list, especially if we give campaigns access to this feature.

- Once the Spoke campaign is selected, a warning will appear with counts confirming you want to overwrite the existing contacts (if any).

- Once the sync is done you will immediately see in the Contacts section of the campaign settings the counts and ability to assign them, as if you had uploaded a csv.

- Note that the list will only send voters with mobile_phone data that has not been marked bad in Votivate.

- It adds the timezone offset field like it would do if uploading via Spoke UI, which you requested as necessary.

- It also now checks the Spoke global opt outs table for any existing opt-outs and removes them with a count on the "success" step of the modal.

- All counts and mobile phone / cell pulls in Votivate already have the numbers marked as bad removed, so there's no action necessary on your part to make this happen. If this ends up being a problem I can work backward and implement a way to pull the bad numbers specifically.

- There is now a Send to Spoke checkbox on user records that can be used to show or hide the button for folks. Right now the feature is only enabled for Robert, Dylan, and I – and only Robert or myself can alter the checkbox while we figure out permission concerns.

**Stakeholder**
@deasterdaywfp

**Comment by codygordon** [comment]
Closing this since we haven't gotten feedback – any additional work on this should be a new feature request.

**Comment by deasterdaywfp** [comment]
@codygordon I think this needs to be reopened -- the sync seems to have issues now. See image included: 
![image](https://user-images.githubusercontent.com/35743690/53915256-96d8b000-402d-11e9-98a2-2194029d6310.png)
cc: @WorkingFamilies/wfp-spoke-team

**Comment by codygordon** [comment]
In the future, things like this should be a bug report so I can track work appropriately. 

I just deployed a patch that should fix the timeout issue. I think it'll still happen for very large universes, but you're not really sending anything bigger than ~30k targets, yeah?

**Comment by deasterdaywfp** [comment]
I see. Sorry I guess that since there was a pertinent issue to attach this
to I reopened it instead of submitting a new bug but will absolutely follow
that process in the future. That is correct typically we wouldn't use this
for universes over 30,000.

**Comment by joemcl** [comment]
Hey @codygordon why not use the existing OSDI API to send to Spoke - see https://github.com/MoveOnOrg/Spoke/pull/690

**Comment by codygordon** [comment]
It's not quite existing, and [this API endpoint](https://github.com/MoveOnOrg/Spoke/pull/967/files) is actually what I'd want to be using once it's deployed.

Regardless of how Spoke is interfaced with, the user experience in Votivate will be exactly the same (if not a bit slower using the API) – and the issue yesterday was not related to interfacing with Spoke.

**Comment by joemcl** [comment]
@codygordon thanks, yeah, I was commenting re need to build an API at top.
I think this API endpoint
<https://github.com/MoveOnOrg/Spoke/pull/967/files> is using OSDI but not
sure, asking Larry.
OSDI is an existing API spec, for sure, but yeah has it been fully
implemented in/for Spoke, no, that's right.
Folks have been working on connecting VAN/Votebuilder to Spoke using OSDI,
and did that successfully for the Salazar for Senate campaign, for example.
The Action Network API is OSDI.
I think my point is that there is a pretty good ecosystem now of platforms
that have implemented parts of OSDI, and it's worth implementing OSDI for
Votivate and the CRM you're building.

**Comment by joemcl** [comment]
Hey @codygordon what's happening with this? Would be great to get it working finally, and with both export and import.

**Comment by joemcl** [comment]
apparently this worked for awhile, and now it does not

**Comment by codygordon** [comment]
If there's a problem, a bug report needs to be filed by someone who is using the feature and can provide some specific context. I'll note that quickly testing it _does_ work, but for some reason inserts into `campaign_contact` are taking a very long time in the Spoke DB, so it's probably timing out for folks. I'll have to investigate and possibly further optimize.

Otherwise, if additional functionality is needed, a new feature request should be opened.

**Comment by deasterdaywfp** [comment]
Cody, thanks but Joe was helping me by filing this while I'm overloaded on
many fronts. The fact is that yes, it may work, but gives a time out error
each time attempted.

**Comment by codygordon** [comment]
No worries. I created the [bug report](https://github.com/WorkingFamilies/votivate/issues/89) for you as an example – this is a non-trivial fix, see my comment on the issue.
