### ISSUE TITLE
Sync "wrong number" responses from Spoke to Votivate

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#18]
**Module**
Core

**Detailed Description**
- This is a job that has been established as 1/19/19 and will run twice daily – once late at night and once during the day. It checks wrong numbers from the past 24 hours. Let me know if we need to run this more frequently. 

- It runs a search on any question response value that contains (case insensitive) 'wrong' AND either '#' OR 'number' in the question text.

- Then it runs a check on the cell number plus Spoke External ID = Votivate ID OR first / last names = Votivate first/last names.

- It will not re-sync matches already marked bad.

- We'll receive 1 email per day now confirming the sync has run with some details on what was synced / errors / etc.

**Stakeholders**
@deasterdaywfp 
@rbrtmnz

**Comment by codygordon** [comment]
The job success email should be more robust – it now includes a CSV of all the synced and attempted synced contacts with some detail as to why a contact isn't found in Votivate, if that's the case.

**Comment by codygordon** [comment]
Closing this since we haven't gotten feedback – any additional work on this should be a new feature request.

**Comment by deasterdaywfp** [comment]
Thanks

*Dylan Easterday*
*National Volunteer Manager, Digital - Working Families Party*
*Working Families <http://workingfamilies.org>*
*Text *(347) 460-9451 or Schedule https://calendly.com/deasterday
Email deasterday@workingfamilies.org
Done with email? me too - join me here <http://bit.ly/WFP4theMany>
