### ISSUE TITLE
Campaigns should be archivable / restorable

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#20]
**Module**

Campaigns

**Detailed Description**

1. From the campaign page there should be an **Archive** button **available only to admins.** This will first ask the user to verify they are sure. If executed, this will also drop the targeting and export pages related to the campaign.

2. There should be a **Show x Archived Campaigns** button that shows archived campaigns and allows users to restore them via a button in the list. Restoring will also re-build the targeting universes when executed.

3. Campaigns should be automatically archived after 30 days of inactivity.

4. There should be a **Auto-Archive** checkbox on a campaign's page. This will be checked by default, but when unchecked the campaign will not be auto-archived after 30 days of inactivity.

5. Campaign users should not be able to select archived campaigns, and if all of their campaigns are archived they should be bounced out with an error message on log in.

**Urgency**

2

**Comment by rbrtmnz** [comment]
I cannot test 3 or 5 but what I could test looks good. I could conceivably test 5 by creating a dummy account but I wanted to check in to see if giving me the ability to impersonate users is an easy update? If not I will just make a dummy account until it can be put onto the development calendar.

**Comment by codygordon** [comment]
Yeah, impersonating users isn't easy. I just use a separate account for testing. Let me know when we're good here and we can close this.
