### ISSUE TITLE
Select tags and canvass results to export

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#32]
**Module**

Exports

**Detailed Description**

1. Below the standard field checkboxes in on the export request modal should be two new dropdowns: one for tags, and one for canvass questions.

1. Selected tags should be populated in the file as a single column with comma separated values.

1. Selected canvass results should each have their own column and contain the answer key along with the timestamp and method of contact. 

1. There should be an **All Answers** checkbox below the canvass result question selector that, if checked, will export _all_ of the person's answers to that question in the single column, comma separated. By default it will be unchecked and only the most recent answer will be exported.

1. Also, there should be a **Notes** checkbox that exports all nodes associated with the person as well as the timestamp and user. These will be in a single column, pipe separated. 

1. As a side-effect, the UI for new exports will be changed from a modal to scrollable page and the menu / button navigation will match that of Bulk Uploads.

**Urgency**

2

**Comment by rbrtmnz** [comment]
I need export approval access in staging to test this. Looks good but wanted to see the results in an actual export. I submitted a request that is awaiting approval.

**Comment by codygordon** [comment]
Woops, removed that.

Hmm, also didn't get the email. Will look into that.

**Comment by rbrtmnz** [comment]
This all seems done but I actually have an issue with items 2, 4, and 5. I am not in favor of organizing several data points into a single cell since the data is not usable that way unless a person knows how to properly reformat it in Excel which more often than not will not be the case. I think the best possible solution for displaying "All Answers" is to give the voter a different row for each response.

**Comment by codygordon** [comment]
That makes sense and I can implement it that way. You'll just always have
people complaining about "dupes" in their exports.

**Comment by rbrtmnz** [comment]
Yes, this is definitely a matter of competing trade-offs. My hope is that most people just do a default export with the latest results, but for those who want all the data, I think this is more usable for the typical person.

Worst case scenario, if they complain with this setup, I can help them de-dupe to remove the extra record. I do not however know how to quickly parse the type of non-uniform data that results from wedging multiple data points into some cells and not others in the same column.

We can probably head off some complaints by having a pop-up when you hover over the all answers check box indicating that clicking this will result in multiple records for voters with multiple responses.

**Comment by codygordon** [comment]
Okay, this is working as requested now. The one major caveat is that if **All Answers** is selected, only one question can be selected at a time. Otherwise you'd potentially have a crazy number of rows that would quickly get confusing. 

Also, if there are tags / notes / statuses selected, those will just show up the same in each "duplicated" answer row.

**Comment by codygordon** [comment]
@rbrtmnz – this is deployed, please go ahead and open a bug report if you spot any issues with it.
