### ISSUE TITLE
ID search doesn't work well

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#40]
**Detailed Description**

Searching for Votivate ID only works when copy/pasted directly into the search bar, and even then only if the search page isn't currently open.

**Comment by codygordon** [comment]
Should work much better now.

**Comment by rbrtmnz** [comment]
ID searches are not loading anything. I attempted to search by name and it loaded instantly.

**Comment by rbrtmnz** [comment]
good to go
