### ISSUE TITLE
Tagged Voters Not Returned in Query

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#47]
**Environment:**
 - Windows
 - Chrome

**Detailed Description**
Filtering by the question Nixon ID formerly returned results but does not return anything now.

**Does It Have a Workaround?**
I could try to re-upload that data but I am raising this because the same issue occurred last week.

**Screenshots**
![image](https://user-images.githubusercontent.com/30630157/52380399-930c3a80-2a3b-11e9-98d4-ccbef9e52bff.png)

**Comment by codygordon** [comment]
These were all uploaded to the "Ulster Sheriff" campaign, so this is more or less a reference to these two feature requests: 
https://github.com/WorkingFamilies/votivate/issues/10
https://github.com/WorkingFamilies/votivate/issues/11

**Comment by codygordon** [comment]
FYI removed the campaign from the ones uploaded to the Ulster Campaign so they now show up for all campaigns in NY. See: https://workingfamilies.votivate.com/targeting/universe-builder/5c5b692343152d33b390e64b
