### ISSUE TITLE
New User Did Not Receive Invite

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#49]
**Environment:**
 - Windows 
 - Chrome

**Detailed Description**
I sent Ari two invites to join Votivate but he received neither.

**Does It Have a Workaround?**
Apparently, since he has gone this long without having access.

**Screenshots**
![image](https://user-images.githubusercontent.com/30630157/52668332-87ec5b00-2ed0-11e9-99d4-7f9bcdc9fbbe.png)

**Comment by codygordon** [comment]
Another legacy user that needed to be manually switched over. Last one this time?

**Comment by rbrtmnz** [comment]
I totally forgot that was a thing.
