### ISSUE TITLE
Exports download loading indicator

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#55]
**Module**

Exports

**Detailed Description**

When the Download button is clicked on an export, a loader should display indicating the file is loading, rather than just leaving the user guessing as to what's happening.

**Comment by rbrtmnz** [comment]
I attempted several downloads and did not see this. Small files downloaded instantly and on larger files nothing happens until it eventually downloads.

**Comment by rbrtmnz** [comment]
I cant test this without the ability to approve exports.

**Comment by rbrtmnz** [comment]
I had a spinning wheel when attempting to download a fairly large export.
