### ISSUE TITLE
Default sorting for lists

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#56]
**Module**

Core

**Detailed Description**

Lists should have default sorting set

**Comment by rbrtmnz** [comment]
What are the sorting parameters you chose? What lists does this refer to?

**Comment by codygordon** [comment]
Any list (table) in the app where sorting in possible, i.e. campaigns, targeting, etc. You can see what sorting params were chosen by default – mainly whatever makes sense like name, created date, etc. In the future I want to add a feature that saves whatever sorting the user chooses so this ends up being less relevant.
