### ISSUE TITLE
Tabs / other non-space whitespace throw error on search

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#59]
**Detailed Description**

Somestimes people may copy/paste tabs or other non-space whitespace into searchbar and it returns a server error. It should just convert any whitespace into regular spaces before processing.

**Does It Have a Workaround?**

Type in a space to replace tabs, etc.

**Comment by rbrtmnz** [comment]
Not sure if I approached this correctly but I copy/pasted in names from Excel that had extra invisible characters and did not receive an error message.

**Comment by codygordon** [comment]
Yeah, not sure where the characters were coming from (I guess Excel if
that's where people are copy/pasting from?), but testing the characters
sent previously that caused errors using the backend API url on my end and
it converts them to spaces properly.
