### ISSUE TITLE
make staff/user Last Login display as datetime field so it sorts by last login date and time...

### ISSUE THREAD

**Issue by joemcl** [WorkingFamilies/votivate#60]
**Module**
https://workingfamilies.votivate.com/staff 

**Detailed Description**
make Last Login display as date field so it sorts by date and time - looked like it was sorting numerically before - maybe that was already fixed - also add time to display - so last login date and time...

**Urgency**
1

related to #1

**Comment by rbrtmnz** [comment]
This works

**Comment by joemcl** [comment]
thanks @codygordon
