### ISSUE TITLE
enable California Admin user, screen displays no data 

### ISSUE THREAD

**Issue by joemcl** [WorkingFamilies/votivate#61]
**Module**
https://workingfamilies.votivate.com/staff

**Detailed Description**
enable California Admin user, screen displays no data - 

![adc80c09-5a8f-4d75-8957-819bb7a1a513](https://user-images.githubusercontent.com/3912434/53360110-87e55580-38e9-11e9-9df9-fc403577c59c.jpg)

**Urgency**
1

**Comment by joemcl** [comment]
Hey @deasterdaywfp @codygordon - is this ever going to happen? I actually have an immediate use case that I can explain to you offline, @deasterdaywfp .

**Comment by codygordon** [comment]
Should work, just check in w/ leadership to make sure everything's kosher with the use-case.

**Comment by joemcl** [comment]
Ok thanks so much @codygordon
