### ISSUE TITLE
User state / campaign / targeting / route path should save/reload when logged out

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#62]
**Module**

Core

**Detailed Description**

- Admin users' state / campaign are  saved / reloaded when logged out / in.
- Campaign or admin users' targeting / route path are saved / reloaded when logged out / in.

**Urgency**

1

**Comment by rbrtmnz** [comment]
Looks good

**Comment by codygordon** [comment]
Deployed, but could be some wonkiness to look out for if some weird non-route is saved before logging out.
