### ISSUE TITLE
Notes section on Voter record

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#63]
**Module**

Voter Lookup

**Detailed Description**

- There should be a **Notes** menu item after **Contact History**
- There should be a menu above the list with a text input to add a note. 
- For admins, there should be a dropdown to optionally select a campaign (useful if you only want a specific campaign to see a note).
- The list should show Timestamp, Created By, and the note text.

**Urgency**

2

**Comment by rbrtmnz** [comment]
Looks good.
