### ISSUE TITLE
Add New Jersey Voterfile

### ISSUE THREAD

**Issue by deasterdaywfp** [WorkingFamilies/votivate#65]
@codygordon 

**Module**

* List

**Detailed Description**

Please update the Votivate file with NJ voter records with all available party data for an upcoming project :) 

**Urgency**

2

**Comment by rbrtmnz** [comment]
Urgency - 1

They emailed me about getting moving on this so I upped the urgency.

**Comment by deasterdaywfp** [comment]
Thank you

**Comment by codygordon** [comment]
That would be urgency = 3... but I'll get it in later today.

**Comment by codygordon** [comment]
It's in, looks good w/ cursory testing.

**Comment by deasterdaywfp** [comment]
Thanks!
