### ISSUE TITLE
Tags Not Appearing on Walk Sheet

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#66]
**Environment:**
Chrome

**Detailed Description**
The sheet format in CT titled PFML Field Canvass is currently set to include four tags but nothing shows when printed or sent to mobile.

**Does It Have a Workaround?**
Campaign is currently using a question in place of the four tags.

**Screenshots**
![image](https://user-images.githubusercontent.com/30630157/53849862-40586c80-3f6e-11e9-94b3-19523c22d69b.png)

![image](https://user-images.githubusercontent.com/30630157/53849896-65e57600-3f6e-11e9-9d7e-82d9dce8a1c2.png)

**Comment by codygordon** [comment]
The tags are marked as **Read Only** – this means they're for informational purposes only (there's usually a popup explaining, though it looks to be broken in prod right now (fixed on staging).

See an example of when a tag _will_ appear, when a tag is added to the record of a person on the turf. See: 
![screen shot 2019-03-06 at 10 44 21 am](https://user-images.githubusercontent.com/13374656/53901760-eeaaf300-3ffc-11e9-8e18-39c956b579a4.png)
![screen shot 2019-03-06 at 10 44 16 am](https://user-images.githubusercontent.com/13374656/53901773-f5396a80-3ffc-11e9-919b-7d5e96094e21.png)

**Comment by codygordon** [comment]
Also realizing these should not be set to **Read Only** by default. See: https://github.com/WorkingFamilies/votivate/issues/67
