### ISSUE TITLE
Tags on sheets should not default to Read Only

### ISSUE THREAD

**Issue by codygordon** [WorkingFamilies/votivate#67]
**Module**

Settings - Sheets

**Detailed Description**

To avoid confusion, the **Read Only** checkbox should need to be explicitly selected as it's the currently the default and causes confusion.

**Urgency**

2

**Comment by rbrtmnz** [comment]
This has to do with whether or not the tags show on the sheet right? I feel like having the option to click "Read Only" is still confusing as is. I think this should either be removed or it needs more explanation as to what checking the box does. Something like "When this box is checked the tag will only appear on walk lists for contacts already assigned this tag."

**Comment by codygordon** [comment]
Yeah. I think there are two real use-cases for tags: a) either canvassers are collecting in the field, or b) a tag (i.e. ` Donor`) is displayed for informational purposes. For **b** you don't want the canvasser to be able to check the box nor data entry to be able to enter it, thus the `Read Only` option.

Perhaps the nomenclature could be more user-friendly; open to suggestions. Otherwise, the current help text is `If set to Read Only the tag will only show up on the sheet when data exists and it won't be a data entry option.`, which you'll see if looking at it in Staging.

**Comment by rbrtmnz** [comment]
I got you. That makes sense for use case.

I had not floated over the check box and seen the pop up. This looks good to go.
