### ISSUE TITLE
Missing Campaign

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#68]
**Environment:**
Chrome

**Detailed Description**
CT had a campaign titled Osten - Field PFML that disappeared. They lost the cut turfs and have had to create subsequent universes of the same name for turf cutting. The universe do not appear to be hidden or archived.

**Does It Have a Workaround?**
Creating new universe for turf cutting. Nothing for recovering previously cut turfs.

**Screenshots**

**Comment by codygordon** [comment]
I see both – what are they seeing? 

![screen shot 2019-03-06 at 11 46 32 am](https://user-images.githubusercontent.com/13374656/53905290-69780c00-4005-11e9-893f-129692e5b9bf.png)

**Comment by codygordon** [comment]
Also I see universes and turfs for the first one. Are you also not seeing them?
