### ISSUE TITLE
Votivate to Spoke list sync needs to add +1 prefix

### ISSUE THREAD

**Issue by deasterdaywfp** [WorkingFamilies/votivate#69]
without the prefix replies do not come back into the spoke campaign. Upon using the integration the list does not add that prefix automatically

**Comment by bdatkins** [comment]
Background: Records in campaign_contact and message don't have the +1 prefix, but when a reply comes in from Twilio, it has the prefix.  It looks up the last message by cell # in the message table and it doesn't find it, so the message row is never created.

**Comment by deasterdaywfp** [comment]
Thank you for that Barbara!

**Comment by deasterdaywfp** [comment]
@rbrtmnz @AriKamen @codygordon Highlighting for you.

**Comment by codygordon** [comment]
Thanks for testing out the functionality – this fix has been deployed. Let us know if it works.

**Comment by deasterdaywfp** [comment]
@Cody Gordon <cody@votivate.com> Thank you! I will test this for our next
smaller turnout campaign list -- @Barbara Atkins <bdatkins@gmail.com> would
you be able to see the result in Heroku postgres tables before we send to
tell if this added prefix correctly to be usable by Twilio & Spoke?

*Dylan Easterday*
*National Volunteer Manager, Digital - Working Families Party*
*Working Families <http://workingfamilies.org>*
*Text *(347) 460-9451 or Schedule https://calendly.com/deasterday
Email deasterday@workingfamilies.org
Done with email? me too - join me here <http://bit.ly/WFP4theMany>

**Comment by deasterdaywfp** [comment]
Testing sync to Spoke on this campaign: 
![image](https://user-images.githubusercontent.com/35743690/54379351-9eb4d780-465f-11e9-8b9b-3a5ab65a36fa.png)

**Comment by bdatkins** [comment]
@deasterdaywfp Yeah, I can check it once you load in the contacts

**Comment by bdatkins** [comment]
1225 looks good @deasterdaywfp

**Comment by deasterdaywfp** [comment]
@bdatkins Awesome! @codygordon Thank you for that patch 👍
