### ISSUE TITLE
WV Municipalities

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#72]
**Module**
Targeting

**Detailed Description**
WV does not have the ability to filter by municipalities lower than county. If this data exists please include it. If it does not please let me know.

**Urgency**
2

**Comment by codygordon** [comment]
The TS file doesn't contain any `township` or `municipal district` data for WV.

Sidenotes: 
- I have to spin up a special database to check the raw files, so to verify a TS data discrepancy before reporting here you should be able to quickly query the district fields in Civis first.
- The WV voterfile will be updated w/ 2018 voting history in mid-April.

**Comment by rbrtmnz** [comment]
The WV team said this was expected because the state data is trash and asked if you could you use the data from the voter or mailing address as a proxy?

Got it on using Civis to answer questions like this going forward.

**Comment by codygordon** [comment]
Sure, if they think the post office city designation will work that's doable. The more accurate way would be knowing which precincts are inside city limits.

**Comment by rbrtmnz** [comment]
I somehow doubt the great state of Wes Virginie has good precinct information but hold on this for a day. I will do some research and talk to Ryan to see if he can source the data from somewhere.

**Comment by rbrtmnz** [comment]
I didn't find anything here and Ryan never got back to me so whatever is in their voting address is fine for municipality.

**Comment by codygordon** [comment]
This is done. Note, I refreshed the WV file at the same time but it hasn't been updated since Oct. It looks like it isn't slated for an update in the near future, so they won't have all the 2018 voting history for a bit.
