### ISSUE TITLE
Campaigns Disappearing 

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#74]
**Environment:**
Chrome

**Detailed Description**
We've had some glitches with Votivate today with the following campaigns disappearing:

1) "Cassano - Field Canvass - SPT" created today by Luis & later archived
2) "Cassano - Field PFML" (or something similar) created today by me

For the first campaign:
We cut turf for the campaign created by Luis & assigned a turf to me to test that it was working properly. We then noticed a typo in the campaign name, so we archived it. It no longer shows up on the Campaigns page in "Archived Campaigns" in my account or Luis' account.

However, it does show up on the Targeting page as an option in the drop down menu, "select a campaign." There are actually 3 campaigns Luis created that are archived that are visible in this drop down menu but know where else for either of us

For the second campaign:
I created a new campaign, "Cassano - Field PFML," saved it, built a universe, and then cut turf. It disappeared, so I repeated the process a second time, assuming user error on my end. 

Neither of the two I created exist on the "Campaigns" page in active or archived campaigns nor on the "Targeting" page in the drop down menu to select a campaign.

In the interest of time, our canvassers on this campaign are canvassing without the app today. You may recall from our video chat a couple weeks ago, this had happened to me then too.
**Does It Have a Workaround?**

**Screenshots**

**Comment by codygordon** [comment]
I need to deploy the massive set of changes sitting in staging, but am sure we'll see a bunch of bugs because everything hasn't been fully tested, thus the delay. Anyway, enough has been reworked around this part of the backend that this bug is probably already solved, just not deployed to prod.

**Comment by rbrtmnz** [comment]
Ugh, I'm the worst. I am slammed until Thursday early and then will make every effort to work through the backlog the last couple days of the week.

**Comment by codygordon** [comment]
PS I'm realizing now that this is also probably just confusion between `hidden` and `archived` campaigns. Hiding campaigns was a feature you requested, but after implementing I realized that something like this would probably happen if it wasn't properly explained to folks aside from Georgia (who I believe had requested it?). 

Essentially, archiving a campaign "deletes" it – it's no longer accessible by anyone, and all the cached targeting universes are deleted.

Just the "hide" feature is a convenience for a cluttered list view, and just hides it from the list currently being viewed by only that user (in this case, Luis just hid the campaign for himself from the campaigns list), and the view can be toggled using this feature:
Prod: 
![Screen Shot 2019-03-20 at 11 21 15 AM](https://user-images.githubusercontent.com/13374656/54709145-399b2f00-4b02-11e9-8868-4f9edc4fedc5.png)

Staging:
![Screen Shot 2019-03-20 at 11 20 18 AM](https://user-images.githubusercontent.com/13374656/54709129-33a54e00-4b02-11e9-8bcd-d9e3f635fbbe.png)
