### ISSUE TITLE
OH Party Affiliation

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#77]
**Module**
Targeting

**Detailed Description**
VAN uses primary election data to assign party affiliation in OH. Our affiliate in OH requested this for Votivate. People in OH can choose to vote in either party's primary. They should be assigned the party of the most recent primary they voted in. Ballot flipping is not uncommon so there will be people who have voted in both D and R primaries. Votivate should disregard the old party affiliation when someone switches to vote in the other parties primary.

**Urgency**
2

**Comment by rbrtmnz** [comment]
I didn't want to put the urgency any higher than 2 because they can get mostly to where they need without this feature but they made a couple of asks and the other ask would seem to be more involved so this would be great to get them.

**Comment by codygordon** [comment]
This is done (in addition to updating the OH vf – now includes all avail 2018 voting history). Here's what we've got:

| party |  count  |
| :---: | :---:   |
| unk   | 3715315 |
| rep   | 2059773 |
| nop   | 3309798 |
| dem   | 1520420 |
| grn   |    7183 |
| lbt   |    2562 |
| oth   |     397 |
| ind   |      63 |
