### ISSUE TITLE
Add totals for crosstab counts columns

### ISSUE THREAD

**Issue by joemcl** [WorkingFamilies/votivate#95]
**Module**

Reports -> Crosstab Counts

**Detailed Description**

Please add totals for columns for Crosstab Counts reports

**Urgency**

1
![dc7aed81-e4ee-431b-ba54-c2d3e5fbc244](https://user-images.githubusercontent.com/3912434/59820140-9663dc80-92df-11e9-94db-72946f3759b0.jpg)

**Comment by codygordon** [comment]
This is deployed

**Comment by joemcl** [comment]
@codygordon thanks so much!
