### ISSUE TITLE
Add Address to Search Results

### ISSUE THREAD

**Issue by joemcl** [WorkingFamilies/votivate#96]
**Module**

Search Results

**Detailed Description**

Add Address to search results list

**Urgency**

1

![7de26a0a-86fa-403c-b34e-dc56bb4450d7](https://user-images.githubusercontent.com/3912434/59821442-68cb6300-92e0-11e9-9490-91a0a308f707.jpg)

**Comment by codygordon** [comment]
This is deployed

**Comment by joemcl** [comment]
terrific @codygordon thanks so much!
